name: Deploy Image to AWS ECR

on:
  push:
    branches: [ main ]
env:
  AWS_REGION: "us-east-2"
permissions:
     id-token: write
     contents: read
jobs:
  
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
    
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          role-to-assume: arn:aws:iam::408309576403:role/lrl-cluwe-developers
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: spring-boot-test-app
        IMAGE_TAG: sample-image
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
