name: my-project
on:

  push:
    branches:
      - main


permissions:
  id-token: write
  contents: read

jobs:
  build_and_deploy:
    strategy:
      matrix:
        module: [ 'Esign' ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Environment Variables
        run: |
          # Source the properties file to set environment variables
          source .github/workflows/properties.txt
          
          # Access the variables
          echo "ECR_REPOSITORY: ${{matrix.module}}_ECR_REPOSITORY"
          echo "DOCKERFILE_PATH: ${{matrix.module}}_DOCKERFILE_PATH"
          echo "ECS_SERVICE: ${{matrix.module}}_ECS_SERVICE"
          echo "CONTAINER_NAME: ${{matrix.module}}_CONTAINER_NAME"
          echo "ECS_TASK_DEFINITION: ${{matrix.module}}_ECS_TASK_DEFINITION"
   

          
