name: Deploy Image to AWS ECR

on:
  push:
    branches: [ main ]
env:
  AWS_REGION: us-east-2
  ECS_TASK_DEFINITION: esign-task-definition
  CONTAINER_NAME: esign-service-container
  ECR_REPOSITORY: spring-boot-test-app
  ECS_SERVICE: esign-service
  ECS_CLUSTER: lrl-cluwe-modernization

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::408309576403:role/lrl-cluwe-dev-r4
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Images
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: spring-boot-test-app
        run: |
            CURRENT_VERSION=(./.github/workflows/version.txt)
            echo "CURRENT_VERSION=$CURRENT_VERSION" 
            echo "$CURRENT_VERSION"
            NEW_VERSION=$((CURRENT_VERSION + 1))
            echo "$NEW_VERSION" >> ./.github/workflows/version.txt
            IMAGE_TAG="latest-V1.${NEW_VERSION}"
            echo "Generated Tag: $IMAGE_TAG"
            echo "IMAGE_TAG=$IMAGE_TAG" >> "$GITHUB_ENV"
            IMAGE_URI="$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" 
            echo "${IMAGE_URI}"
