name: my-project
on:

  push:
    branches:
      - dev


permissions:
  id-token: write
  contents: read

jobs:
  build_and_deploy:
    strategy:
      matrix:
        module: ['Esign']
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Environment Variables
        run: |
         
          properties_file=".github/workflows/properties.txt"
          source "$properties_file"
          
          ECR_REPOSITORY=$(echo "${{ matrix.module }}_ECR_REPOSITORY" | awk -F':' '{print $2}')
          echo $ECR_REPOSITORY 
          DOCKERFILE_PATH=$(echo "${{ matrix.module }}_DOCKERFILE_PATH | awk -F':' '{print $2}')"
          echo $DOCKERFILE_PATH 
                
   
          # Export the environment variables to GitHub Actions environment
          echo "ECR_REPOSITORY=$ECR_REPOSITORY" >> $GITHUB_ENV
          echo $ECR_REPOSITORY 
          echo "DOCKERFILE_PATH=$DOCKERFILE_PATH" >> $GITHUB_ENV
          echo $DOCKERFILE_PATH
          
