name: my-project
on:

  push:
    branches:
      - main


permissions:
  id-token: write
  contents: read

jobs:
  build_and_deploy:
    strategy:
      matrix:
        module: ['Esign']
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Environment Variables
        run: |
         
          source .github/workflows/properties.txt
          
          ECR_REPOSITORY=$(grep ${{ matrix.module }}_ECR_REPOSITORY | cut -d':' -f2) 
          echo "ECR_REPOSITORY=$ECR_REPOSITORY"
          echo "$ECR_REPOSITORY"
          
